version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - inventory-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - inventory-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=your_jwt_secret_key_here_make_it_long_and_secure_in_production

  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - inventory-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/order_service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # Inventory Service
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - inventory-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/inventory_service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - inventory-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/auth_service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=your_jwt_secret_key_here_make_it_long_and_secure_in_production
      - JWT_EXPIRATION=86400000

  # Frontend
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - inventory-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api

networks:
  inventory-network:
    driver: bridge

volumes:
  mongodb_data:
