server:
  port: 8084

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_service
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
